services:
  - type: web
    name: buildplanwizard
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web.app:app --timeout 300 --workers 1
