services:
  - type: web
    name: buildplanwizard
    env: python
    plan: free
    aptPackages:
      - poppler-utils
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web.app:app

  - type: worker
    name: buildplanwizard-analysis-worker
    env: python
    plan: free
    aptPackages:
      - poppler-utils
    buildCommand: pip install -r requirements.txt
    startCommand: python -m web.worker